import type { Metadata } from 'next';
import { TechBadge, TechBadgeGroup } from '@/components/mdx/tech-badge';
import { Timeline, TimelineItem } from '@/components/mdx/timeline';
import Header from '@/components/header';
import Footer from '@/components/footer';

export const metadata: Metadata = {
  title: 'About',
  description: 'Daniele Tulone — AI-native engineer with 6+ years building agentic workflows, AI-powered products, and secure systems. CTO, consultant, open-source contributor.',
  alternates: { canonical: '/about' },
};

export default function AboutPage() {
  return (
    <div className="min-h-screen flex flex-col p-4 sm:p-8 gap-y-8 sm:gap-y-16">
      <Header />

      <main className="flex-1">
        {/* Intro */}
        <section className="grid grid-cols-1 md:grid-cols-12 gap-4 md:gap-6 mb-16 sm:mb-24">
          <div className="md:col-span-3 animate-fade-up sticky top-[4.5rem] sm:top-[6.5rem] self-start z-10 bg-background py-2 sm:py-0">
            <h1 className="text-3xl sm:text-4xl font-bold text-foreground">I&apos;m Daniele</h1>
            <p className="text-sm text-muted mt-2">Engineer, builder, relentless experimenter.</p>
          </div>

          <div className="md:col-span-6 md:col-start-6">
            <div className="space-y-4 text-sm text-muted animate-fade-up" style={{ animationDelay: '120ms' }}>
              <p>
                I work at the frontier of AI-assisted development — designing agentic workflows, crafting Claude Code skills, and shipping products where 95% of the code is generated by AI. I don&apos;t just use AI tools; I build them, extend them, and push their limits daily.
              </p>
              <p>
                Over six years of professional experience across startups (as CTO, founder, and consultant) taught me one thing: the size of a company doesn&apos;t define the depth of the work. I&apos;ve architected backend systems, built real-time platforms, designed frameworks used by other developers, and led teams — always with a bias toward experimentation and shipping.
              </p>
              <p>
                Today my focus is sharp: <strong className="text-foreground">agentic code</strong>, <strong className="text-foreground">security</strong>, and <strong className="text-foreground">compliance</strong>. I build systems that are fast to create, safe to deploy, and ready for production.
              </p>
            </div>

            <div className="animate-fade-up" style={{ animationDelay: '200ms' }}>
              <TechBadgeGroup>
                <TechBadge variant="highlight">Agentic AI</TechBadge>
                <TechBadge variant="highlight">Claude Code</TechBadge>
                <TechBadge variant="highlight">Security &amp; Compliance</TechBadge>
                <TechBadge variant="highlight">TypeScript</TechBadge>
                <TechBadge variant="highlight">Python</TechBadge>
                <TechBadge>LLMs</TechBadge>
                <TechBadge>MCP</TechBadge>
                <TechBadge>Next.js</TechBadge>
                <TechBadge>Node.js</TechBadge>
                <TechBadge>Flutter</TechBadge>
                <TechBadge>Docker</TechBadge>
                <TechBadge>AWS</TechBadge>
              </TechBadgeGroup>
            </div>

            <div className="space-y-4 text-sm text-muted animate-fade-up" style={{ animationDelay: '280ms' }}>
              <p>
                People who work with me know: I experiment constantly, I learn fast, and I deliver. The experiences may look unconventional on paper — but each one was a deep dive, not a surface skim.
              </p>
              <p>
                Outside of code: music (prog, jazz, Italian classics), minimal aesthetics, and cross-disciplinary learning.
              </p>
            </div>
          </div>
        </section>

        {/* Work Experiences */}
        <section className="grid grid-cols-1 md:grid-cols-12 gap-4 md:gap-6 mb-16 sm:mb-24">
          <div className="md:col-span-3 animate-fade-up sticky top-[4.5rem] sm:top-[6.5rem] self-start z-10 bg-background py-2 sm:py-0">
            <h2 className="text-2xl font-bold text-foreground">Work</h2>
            <p className="text-xs text-muted mt-2">AI-driven products, startup leadership, and hands-on engineering</p>
          </div>

          <div className="md:col-span-6 md:col-start-6">
            <Timeline>
              <TimelineItem title="CTO — Spods" period="Ongoing">
                <p>
                  Leading the technical vision behind <a href="https://spodshr.com" className="text-foreground underline hover:text-muted transition-colors">Spods</a>, an AI-powered talent acquisition platform built for employment agencies. Designing the architecture for intelligent candidate matching, automated screening workflows, and scalable hiring pipelines — with a strong focus on compliance and data security.
                </p>
                <TechBadgeGroup>
                  <TechBadge variant="highlight">AI</TechBadge>
                  <TechBadge variant="highlight">Talent Acquisition</TechBadge>
                  <TechBadge>NLP</TechBadge>
                  <TechBadge>LLMs</TechBadge>
                  <TechBadge>Security</TechBadge>
                  <TechBadge>Compliance</TechBadge>
                </TechBadgeGroup>
              </TimelineItem>

              <TimelineItem title="AI Consultant — Independent" period="Ongoing">
                <p>Advising companies on agentic workflows, security, and compliance for AI-driven development.</p>
                <p><strong className="text-foreground">Agentic Development</strong> — Designing and shipping systems where 95% of code is AI-generated. Creating custom Claude Code skills, orchestrating multi-agent pipelines, and building MCP integrations. Deep focus on making AI-assisted development secure, auditable, and production-ready.</p>
                <p><strong className="text-foreground">Security &amp; Compliance</strong> — Embedding security-first principles into AI-driven codebases. Ensuring generated code meets compliance standards, implementing guardrails, and designing review workflows that catch what humans miss.</p>
                <TechBadgeGroup>
                  <TechBadge variant="highlight">Claude Code</TechBadge>
                  <TechBadge variant="highlight">Agentic AI</TechBadge>
                  <TechBadge variant="highlight">MCP</TechBadge>
                  <TechBadge variant="highlight">Security</TechBadge>
                  <TechBadge>LLMs</TechBadge>
                  <TechBadge>Embeddings</TechBadge>
                  <TechBadge>NLP</TechBadge>
                </TechBadgeGroup>
                <p><strong className="text-foreground">Open source</strong> — Built <a href="https://github.com/danieletulone/tool1-marketplace" className="text-foreground underline hover:text-muted transition-colors">tool1-marketplace</a>, a Claude Code plugin marketplace to build, publish, and install plugins that automate development workflows. Created <a href="https://github.com/danieletulone/claude-code-marketplace-template" className="text-foreground underline hover:text-muted transition-colors">claude-code-marketplace-template</a>, a template for spinning up your own Claude Code plugin marketplace.</p>
              </TimelineItem>

              <TimelineItem title="Freelance Full-Stack Developer" period="Ongoing">
                <p>Supporting startups and companies in building modern, scalable digital products — from backend architecture to frontend delivery.</p>
                <p><strong className="text-foreground">AI &amp; NLP</strong> — LLM workflows (GPT, LLaMA, Mistral) for information extraction, text generation, and prompt engineering. Semantic search with multilingual embeddings. OCR pipelines with LLM-based normalization. Voice-based automation integrating Speech-to-Text with Telegram. Real-time analytics with Redis and event sourcing.</p>
                <TechBadgeGroup>
                  <TechBadge variant="highlight">TypeScript</TechBadge>
                  <TechBadge variant="highlight">Python</TechBadge>
                  <TechBadge variant="highlight">Next.js</TechBadge>
                  <TechBadge>Node.js</TechBadge>
                  <TechBadge>Redis</TechBadge>
                  <TechBadge>OpenAPI</TechBadge>
                  <TechBadge>OCR</TechBadge>
                </TechBadgeGroup>
              </TimelineItem>

              <TimelineItem title="Founder & CTO — BubblePod S.r.l." period="2022 – 2024">
                <p>Social network built around collaborative audio, later evolving into a real-time 1-to-1 video platform. Designed an event-sourcing backend, integrated WebSockets with Soketi, built the Flutter app with battery optimization, and implemented HLS adaptive bitrate streaming for short-form video.</p>
                <TechBadgeGroup>
                  <TechBadge variant="highlight">Flutter</TechBadge>
                  <TechBadge>Event Sourcing</TechBadge>
                  <TechBadge>WebSockets</TechBadge>
                  <TechBadge>HLS</TechBadge>
                  <TechBadge>Redis</TechBadge>
                  <TechBadge>In-App Purchases</TechBadge>
                </TechBadgeGroup>
              </TimelineItem>

              <TimelineItem title="CTO — Marlon" subtitle="University Project" period="2021 – 2022">
                <p>Collaborative ecosystem for frontend development — a hybrid visual editor and intelligent code generator. Built a Figma-style editor with a plugin system and custom WebGL engine at 60 FPS. Integrated TensorFlow WebAssembly for hand-drawn element recognition, and early NLP workflows (pre-GPT, using NLTK) for generating frontend code from natural language.</p>
              </TimelineItem>

              <TimelineItem title="Open Source" subtitle="Pre-AI era" period="2020 – 2022">
                <p>Built <a href="https://github.com/stratumfoundry/velvet" className="text-foreground underline hover:text-muted transition-colors">Velvet</a>, a modular Flutter framework that reduced delivery time by 40% and cut bugs by 50%. Created <a href="https://github.com/promptify-it/pfy" className="text-foreground underline hover:text-muted transition-colors">pfy</a>, a command-sharing terminal tool for developer collaboration. All hand-written, before the AI explosion.</p>
                <TechBadgeGroup>
                  <TechBadge variant="highlight">Flutter</TechBadge>
                  <TechBadge variant="highlight">Dart</TechBadge>
                  <TechBadge>CLI</TechBadge>
                  <TechBadge>Open Source</TechBadge>
                </TechBadgeGroup>
              </TimelineItem>

              <TimelineItem title="Full-Stack Developer → CTO — DonkeyCommerce S.r.l." subtitle="First professional experience" period="Early career">
                <p>Milan-based e-commerce startup. Started as a full-stack developer, promoted to CTO within months. Rebuilt the entire API and CMS architecture, led a team of four, and improved performance and reliability across the stack.</p>
              </TimelineItem>
            </Timeline>
          </div>
        </section>

        {/* Education */}
        <section className="grid grid-cols-1 md:grid-cols-12 gap-4 md:gap-6">
          <div className="md:col-span-3 animate-fade-up sticky top-[4.5rem] sm:top-[6.5rem] self-start z-10 bg-background py-2 sm:py-0">
            <h2 className="text-2xl font-bold text-foreground">Education</h2>
            <p className="text-xs text-muted mt-2">From classical studies to computer science, design, and coding</p>
          </div>

          <div className="md:col-span-6 md:col-start-6">
            <Timeline>
              <TimelineItem title="Media Design — IED Milano" subtitle="Istituto Europeo di Design" period="Degree · 105/110">
                <p>Won a full scholarship at a hackathon. IED offered a multidisciplinary environment where technical, creative, and conceptual skills meet. Key courses that shaped my approach:</p>
                <ul className="list-disc pl-4 space-y-1">
                  <li><strong className="text-foreground">History of Cinema</strong> — understanding how hardware, narrative, light, and sound shape communication</li>
                  <li><strong className="text-foreground">Emotional Intelligence</strong> — leadership, collaboration, and managing creative-technical teams</li>
                  <li><strong className="text-foreground">Design Thinking</strong> — structured innovation, including Google Design Sprint methodology</li>
                  <li><strong className="text-foreground">Interactive Installation</strong> — video, audio, and coding at the intersection; first time leading a hybrid team</li>
                </ul>
                <TechBadgeGroup>
                  <TechBadge>HTML/JS</TechBadge>
                  <TechBadge>Laravel</TechBadge>
                  <TechBadge>PyGame</TechBadge>
                  <TechBadge>Unity</TechBadge>
                  <TechBadge>Git</TechBadge>
                  <TechBadge>AWS</TechBadge>
                </TechBadgeGroup>
              </TimelineItem>

              <TimelineItem title="Computer Science — UNIMI" subtitle="University of Milan" period="1 Year">
                <p>Strengthened logical-mathematical foundations and got a structured introduction to formal software development.</p>
              </TimelineItem>

              <TimelineItem title="Classical Studies — Liceo Classico T. Fazello" subtitle="High School Diploma" period="Diploma">
                <p>Latin literature, ancient Greek, philosophy, and the analytical discipline of a classical education. That background shaped my thinking: structured, curious, rigorous.</p>
                <p>Also attended an intensive memory and learning course — advanced techniques for memory organization and reading efficiency that later influenced how I learn, design, and code.</p>
              </TimelineItem>

              <TimelineItem title="Self-Taught Coding" subtitle="Autodidact journey" period="Since age 16">
                <p>Started from game cracking and hacking blogs — not for their &quot;underground&quot; nature but because they revealed how software really works under the surface. From there, learned systematically through W3Schools, YouTube, and Udemy.</p>
              </TimelineItem>
            </Timeline>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
